# Generated by Django 5.0.6 on 2024-05-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_faq_answer'),
        ('shop', '0002_alter_repair_min_price'),
    ]

    operations = [
    ]
