# Generated by Django 5.0.6 on 2024-05-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_merge_20240528_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='discount')),
            ],
        ),
    ]
