# Generated by Django 5.0.6 on 2024-05-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_repair_product_product_repair'),
        ('shop', '0004_statiy'),
    ]

    operations = [
    ]
