# Generated by Django 5.0.6 on 2024-05-30 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_productimages_add_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmemory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_memories', to='shop.product'),
        ),
    ]
