# Generated by Django 5.0.6 on 2024-05-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_productmemory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmemory',
            name='add_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
