# Generated by Django 5.0.6 on 2024-05-30 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_productcolor_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('info_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productinfotype')),
            ],
        ),
    ]
