# Generated by Django 5.0.6 on 2024-05-30 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productinfotype_productinfodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfotype',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
